### ISSUE TITLE
Interpretation of sl, sh and r1

### ISSUE THREAD

**Issue by sxs4337** [uranusx86/Random-Erasing-tensorflow#2]
Can you please help with the interpretation of the three parameters? How do we relate these values with the range of random patch sizes?

**Comment by uranusx86** [comment]
sl and sh are the upper bound and lower bound of erasing area, both are ratio with the respect of the image.
r1 is aspect ratio of erasing area.

**Comment by sxs4337** [comment]
Thanks!
